%rebase layout globals(), css=['system/css/log.css'], title='System Log', menu_part='/system'

%from shinken.bin import VERSION
%helper = app.helper

<div id="content_container">
	<ul class="nav nav-tabs" id="myTab">
		<li class="active"><a href="#today" data-toggle="tab">Today</a></li>
		<li><a href="#yesterday" data-toggle="tab">Yesterday</a></li>
		<li><a href="#thisweek" data-toggle="tab">This Week</a></li>
		<li><a href="#lastweek" data-toggle="tab">Last Week</a></li>
		<li><a href="#custom" data-toggle="tab">Custom</a></li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane active" id="today">
			<table class="table table-striped">
				<tbody>
					<tr>
						<td>1337799656</td>
						<td>Info: Using the local log file 'arbiterd.log'</td>
					</tr>
					<tr>
						<td>1337799656</td>
						<td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
					</tr>
					<tr>
						<td>1337799656</td>
						<td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
					</tr>
					<tr>
						<td>1337799656</td>
						<td>Warning: I autogenerated some Arbiter modules, please look at your configuration</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="tab-pane" id="yesterday">...</div>
		<div class="tab-pane" id="thisweek">...</div>
		<div class="tab-pane" id="lastweek">...</div>
		<div class="tab-pane" id="custom">
			<label>Custom log range</label>
			<div class="row-fluid input">
				<div class="inline-inputs">
					From
					<input name='from_day' data-datepicker="datepicker" class="input input-small" type="text" value="" />
					<input name='from_hour' class="input input-mini" type="text" value="" />
					to
					<input name='to_day' data-datepicker="datepicker" class="input input-small" type="text" value="" />
					<input name='to_hour' class="intput input-mini" type="text" value="" />
				</div>
			</div>
		</div>
	</div>

</div>